bigQuery:
  #  这里是 bigquery账单 所在项目id
  projectID: "your-project-id"
  tableID: "your-table0id"
webhook:
  # 钉钉机器人 webhook
  url: "robot-webhook"
  keyWord: "robot-keyWord"

storage:
  # 每周、每月用量存储位置
  bucket: "your-storage-bucket-name"
  projectID: "your-project-id"

email:
  smtpHost: "your email's hostname"
  smtpPort: 465 # “your email's port"
  username: "your-email-name"
  password: "your-email-password"

recipients:
  - "recipient's email"
