bigQuery:
  #  这里是 bigquery账单 所在项目id
  projectID: "billing-ftl-cloud"
  tableID: "billing-ftl-cloud.Daily_billing_gcp.gcp_billing_export_v1_017DBD_1FB85B_839E84"
webhook:
  # 钉钉机器人 webhook
  url: "https://oapi.dingtalk.com/robot/send?access_token=0e9ea67109249def85b90a476d7da92c706767ecf8e672a6673120a8dfa24a52"
  keyWord: "用量监控"

storage:
  # 每周、每月用量存储位置
  bucket: "billing_usage2email"
  projectID: "billing-ftl-cloud"

email:
  smtpHost: "smtp.qq.com"
  smtpPort: 465
  username: "1103202077@qq.com"
  password: "msnfxohovojvbafb"

recipients:
  - "songnaibing@nebula-data.com"
  - "it@nebula-data.com"
